spring.application.name=Exercise-1-User-Order-Management

spring.datasource.url=jdbc:mysql://localhost:3306/user_order_db
spring.datasource.username=root
spring.datasource.password=varshA@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080