spring.application.name=Exercise-2-Load-Balancing

spring.cloud.gateway.server.webflux.routes[0].id=load_balanced_route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://example-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/loadbalanced/**