spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=customer-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/customers/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/api/(?<segment>.*), /${segment}

spring.cloud.gateway.server.webmvc.routes[1].id=billing-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/billing/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/api/(?<segment>.*), /${segment}